/**
 * Wann ist der Worker fertig? (Spec §7, Schritt 5)
 *
 * Zwei Signale, weil keines allein trägt: REPORT.md sagt „ich halte mich für
 * fertig“, das Idle-Ereignis sagt „der Zug ist zu Ende“. Ein Report mitten im
 * Zug ist möglich, ein Idle zwischen zwei Zügen auch. Fällt das Idle-Ereignis
 * aus (anderer Name in einer neuen opencode-Version — still, wie alles dort),
 * trägt die Ruhezeit.
 */

export const IDLE_SIGNAL_FILENAME = '.cipher-mux-idle'
export const IDLE_PLUGIN_FILENAME = 'cipher-mux-idle.js'
/** Gemessen in Task 0 / Spec §10a (opencode 1.18.35). */
export const IDLE_EVENT_TYPE = 'session.idle'

export function buildIdlePlugin(signalFile: string): string {
  return `// Generated by cipher-mux (local-factory/worker-done.ts). Do not edit.
import * as fs from 'node:fs'

const SIGNAL = ${JSON.stringify(signalFile)}
const TYPE = ${JSON.stringify(IDLE_EVENT_TYPE)}

export default async () => ({
  event: async (raw) => {
    try {
      if (raw && raw.event && raw.event.type === TYPE) {
        fs.writeFileSync(SIGNAL, String(Date.now()), 'utf-8')
      }
    } catch {
      // Signal, keine Zusage — die Ruhezeit trägt ohne.
    }
  },
})
`
}

export type WorkerState = 'arbeitet' | 'fertig' | 'haengt'

export interface WorkerObservation {
  now: number
  startedAt: number
  reportMtime: number | null
  idleSignalAt: number | null
  lastActivityAt: number
}

export function classifyWorker(
  o: WorkerObservation,
  cfg: { quietMs: number; timeoutMs: number; stallMs: number },
): WorkerState {
  if (o.now - o.startedAt > cfg.timeoutMs) return 'haengt'
  const quiet = o.now - o.lastActivityAt
  if (o.reportMtime !== null) {
    if (o.idleSignalAt !== null && o.idleSignalAt >= o.reportMtime) return 'fertig'
    if (quiet > cfg.quietMs) return 'fertig'
    return 'arbeitet'
  }
  // Untätig ohne Report: am Ausgabelimit endet das Modell still (Spec §10a.2).
  if (o.idleSignalAt !== null && quiet > cfg.quietMs) return 'haengt'
  if (quiet > cfg.stallMs) return 'haengt'
  return 'arbeitet'
}
