/**
 * Application-wide constants.
 *
 * WHY no BRAND import here: This file is shared between Main and Renderer.
 * brand.ts uses Node.js APIs (fs, path, process.env) that crash in Renderer.
 * BRAND-dependent values (paths, scan dirs) are resolved in Main process only
 * via brand.ts directly — constants.ts stays Renderer-safe.
 */

/** WHY appName stays "cipher-mux": IPC channels, preload API, and package identity
 *  use this name. Changing it would break all existing configs and integrations.
 *  The profile system controls paths and defaults, not the brand name. */
export const APP_NAME = 'cipher-mux'
/** App version — generated by scripts/git-version.sh at build time */
export { APP_VERSION } from './version'

/** Maximum concurrent sessions */
export const MAX_SESSIONS = 21

/** MCP Server defaults */
export const MCP_DEFAULT_PORT = 3100
export const MCP_DEFAULT_HOST = '127.0.0.1'

/** Context usage warning threshold (percentage) */
export const CONTEXT_WARNING_THRESHOLD = 80

/** Message retention in days */
export const MESSAGE_RETENTION_DAYS = 7

/** Output batching interval for terminal streaming (ms) */
export const OUTPUT_BATCH_INTERVAL_MS = 16

/** Grid save debounce (ms) */
export const GRID_SAVE_DEBOUNCE_MS = 300

/** Message cleanup interval (ms) — every 6 hours */
export const MESSAGE_CLEANUP_INTERVAL_MS = 6 * 60 * 60 * 1000

/** Workshop max retries */
export const WORKSHOP_MAX_RETRIES = 2

/** Cyber Factory max retries per sub-project session */
export const CF_MAX_RETRIES = 2

/** Default scan depth (directory levels below each scanPath that are inspected). */
export const DEFAULT_SCAN_DEPTH = 1
/** Max allowed scan depth (guardrail against runaway recursion). */
export const MAX_SCAN_DEPTH = 5

/** Window defaults */
export const DEFAULT_WINDOW_WIDTH = 1400
export const DEFAULT_WINDOW_HEIGHT = 900

/** Fixed session cell height in pixels — sized so 3 rows fit on QHD (1440p) with macOS taskbar */
export const SESSION_CELL_HEIGHT = 380

/** Grid defaults — 7×3 max for DQHD (5120×1440, 32:9 ultrawide) */
export const DEFAULT_GRID_COLS = 2
export const DEFAULT_GRID_ROWS = 2
export const MAX_GRID_COLS = 7
export const MAX_GRID_ROWS = 3
export const MIN_GRID_COLS = 1
export const MIN_GRID_ROWS = 1

/** Chatroom panel width */
export const CHATROOM_PANEL_WIDTH = 280

/** Default kickoff timeout (minutes) — how long we wait for a completion signal. */
export const KICKOFF_TIMEOUT_MIN_DEFAULT = 15

/** Max manual tags per note (workspace defaultTags don't count) */
export const MAX_MANUAL_TAGS = 5

/** Tag classes where only one value is allowed per note. Adding a second replaces the first. */
export const EXCLUSIVE_TAG_CLASSES = ['status', 'kind']

/** Default persona assignment per preset (from Pack spec 16-persona-presets.md). */
export const PRESET_PERSONA_DEFAULTS: Record<string, string> = {
  companion: 'theaitetos',
  'cyber-factory': 'cipher',
  refinement: 'theaitetos',
  'ideation-partner': 'theaitetos',
  debugger: 'cipher',
  'testing-assistant': 'cipher',
  audit: 'relay',
  'voice-relay': 'relay',
  workshop: 'relay',
  launcher: 'relay',
}

/** Task stall detection defaults */
export const TASK_STALL_TIMEOUT_MS = 300_000       // 5 minutes
export const TASK_WATCH_INTERVAL_MS = 30_000       // 30 seconds
export const TASK_HOOK_TIMEOUT_MS = 60_000         // 60 seconds
export const TASK_DEFAULT_MAX_RETRIES = 2
